version: '3'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
       - $PWD/data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "3306:3306"
    networks:
      - my_net
      
  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "80:80"
    environment:
      PMA_HOST: db
      UPLOAD_SIZE: 1G
      MYSQL_DB_PASSWORD: 123456789
      MYSQL_HOST: db:3306
    networks:
      - my_net
      
networks:
  my_net:
